language: python
python: 3.6

before_install:
  # to build pgmp docs
  - sudo apt-get -y install python3-tk

install:
  make setup

script:
  make

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  target_branch: master
  repo: dvarrazzo/dvarrazzo.github.io
  on:
    branch: master

notifications:
  email: false
